(************************************)

(*INTEGER OPERATIONS AND LISTS TESTS*)
hello! = 2.2/234
2=2
3>4
3>=4
4<5
5<=5
4<>5
!(2@3@4)
!2+3*4/5-3-4)
(***************************************)
withletplusminusnilisnilreadintreadstring
WIThLetPLUsMinUSNIl
LAMBDa
IN
ISnil
ReadINT
REadString(*keywords*)
! !2 !(2@3) 2!#!(*HD*)
23##TL#(*TL*)
()()()()()()()(((((((((())))))))))(((((hello)))((((hi)() (*parens tests)
